# Simulation parameters

[simulation]
  simulated_time = 86400
  dt = 1
  seed = 0
  num_runs = 1
  memory_size = 10

[world]
  worldsize = [1600, 1000, 100]

[agent_class_params]
  classes = ["male_bats", "female_bats", "owls", "insects", "plants"]

[male_bats]
  id = 0
  friends = [  "male_bats" ]
  enemies = [  "owls" ]
  food_sources = [  "insects" ]
  strategy = 3
  status = 1
  num_agents = 250
  audibility = 300
  mu_energy = 100000
  sigma_energy = 1000
  energy_uptake_rate = 10
  mu_levy = 0
  c_levy = 0.5
  brownian_search_duration = 10
  movespeed_search = 0.3
  movespeed_approach_friends = 0.5
  movespeed_avoid_enemies = 1
  movespeed_approach_food = 0.8
  movespeed = 12
  energy_consumption_per_time = 0.1
  energy_consumption_per_distance = 0.1
  size = 0.1
  start_position = [ 0.000000, 0.000000, 0.000000 ]
  random_start_positions = 0
  color = [ 0.500000, 0.750000, 1.000000 ]
  pointsize = 3

[female_bats]
  id = 1
  friends = [  "female_bats" ]
  enemies = [  "owls" ]
  food_sources = [  "insects" ]
  strategy = 3
  status = 1
  num_agents = 250
  audibility = 300
  mu_energy = 100000
  sigma_energy = 1000
  energy_uptake_rate = 10
  mu_levy = 0
  c_levy = 0.5
  brownian_search_duration = 10
  movespeed_search = 0.3
  movespeed_approach_friends = 0.5
  movespeed_avoid_enemies = 1
  movespeed_approach_food = 0.8
  movespeed = 10
  energy_consumption_per_time = 0.1
  energy_consumption_per_distance = 0.1
  size = 0.1
  start_position = [ 0.000000, 1.000000, 0.000000 ]
  random_start_positions = 0
  color = [ 1.000000, 0.750000, 0.800000 ]
  pointsize = 3

[owls]
  id = 2
  friends = [  "owls" ]
  enemies = [  "none" ]
  food_sources = [  "male_bats",  "female_bats" ]
  strategy = 1
  status = 1
  num_agents = 5
  audibility = 50
  mu_energy = 1e+06
  sigma_energy = 1000
  energy_uptake_rate = 1000
  mu_levy = 0
  c_levy = 0.5
  brownian_search_duration = 10
  movespeed_search = 0.5
  movespeed_approach_friends = 0.5
  movespeed_avoid_enemies = 1
  movespeed_approach_food = 1
  movespeed = 15
  energy_consumption_per_time = 1
  energy_consumption_per_distance = 1
  size = 1
  start_position = [ 0.000000, 0.000000, 2.000000 ]
  random_start_positions = 1
  color = [ 1.000000, 0.000000, 0.000000 ]
  pointsize = 5

[insects]
  id = 3
  friends = [  "insects" ]
  enemies = [  "male_bats",  "female_bats" ]
  food_sources = [  "plants" ]
  strategy = 6
  status = 1
  num_agents = 500
  audibility = 100
  mu_energy = 10
  sigma_energy = 1
  energy_uptake_rate = 0.1
  mu_levy = 0
  c_levy = 0.5
  brownian_search_duration = 10
  movespeed_search = 0.3
  movespeed_approach_friends = 0.5
  movespeed_avoid_enemies = 1
  movespeed_approach_food = 0.5
  movespeed = 2
  energy_consumption_per_time = 0.001
  energy_consumption_per_distance = 0.001
  size = 10
  start_position = [ 0.000000, 0.000000, 0.000000 ]
  random_start_positions = 1
  color = [ 1.000000, 0.987342, 0.000000 ]
  pointsize = 2

[plants]
  id = 4
  friends = [  "none" ]
  enemies = [  "insects" ]
  food_sources = [  "none" ]
  strategy = 0
  status = 1
  num_agents = 25
  audibility = 500
  mu_energy = 1000
  sigma_energy = 200
  energy_uptake_rate = 0
  mu_levy = 0
  c_levy = 0.5
  brownian_search_duration = 10
  movespeed_search = 1
  movespeed_approach_friends = 1
  movespeed_avoid_enemies = 1
  movespeed_approach_food = 1
  movespeed = 2
  energy_consumption_per_time = -1
  energy_consumption_per_distance = 0
  size = 50
  start_position = [ 0.000000, 0.000000, 0.000000 ]
  random_start_positions = 1
  color = [ 0.000000, 0.500000, 0.000000 ]
  pointsize = 10

